### ISSUE TITLE
:exec using variable defined in :let causes Exception: variable is not bound

### ISSUE THREAD

**Issue by michaelmesser** [idris-lang/Idris2#890]
# Steps to Reproduce

```idris
Main> :let x : String
Main> :let x = "Test"
Main> :exec putStrLn x
```

# Expected Behavior

```idris
Main> :exec putStrLn x
Test
Main>
```

# Observed Behavior
Chez:
```idris
Main> :exec putStrLn x
Exception: variable Main-x is not bound
Main>
```
Node:
```idris
Main> :exec putStrLn x
/Users/michaelmesser/build/exec/_tmp_node.js:51
try{PrimIO_unsafePerformIO(undefined, Prelude$5fIO_putStrLn(undefined, Prelude$5fIO_$5f$5fImpl$5fHasIO$5fIO(), Main_x));}catch(e){if(e instanceof IdrisError){console.log('ERROR: ' + e.message)}else{throw e} }
                                                                                                                                                                                                      ^

ReferenceError: Main_x is not defined
    at Object.<anonymous> (/Users/michaelmesser/build/exec/_tmp_node.js:51:112)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by michaelmesser** [comment]
I found the bug and will submit a PR with a test
